import { Date as DatePanel, Time as TimePanel, StatusPanel, State as TimeState }
	from "shared.slint";

import { Departure, Panel as DeparturePanel, State as DepartureState, BusStop, BusStopList }
	from "schedule.slint";

export { DepartureState, TimeState }

export component App inherits Window {
	in property <string> status;

	in property <[Departure]> schedule-into-city;
	in property <[Departure]> schedule-from-city;

	title: "Busfahrplan";
	background: #272b30;
	default-font-family: "Noto Sans";
	default-font-size: 26pt;
	// HACK: getting full width
	min-height: 100px;
	min-width: 300px;
	max-width: 10000px;

	// Background
	if root.schedule-into-city.length == 0 && root.schedule-from-city.length == 0 : Text {
		text: "Loading...";
		font-size: 102pt;
		color: #FFFFFF33;
		x: (parent.width - self.width) * 50%;
		y: (parent.height - self.height) * 30%;
		z: 1;
	}

	VerticalLayout {
		alignment: start;
		// Header
		VerticalLayout {
		 	padding-left: 10px;
			padding-right: 10px;

			HorizontalLayout {
				alignment: space-between;

				time := TimePanel {}
				Text {
					text: root.title;
					color: #FFF;
					font-size: 30pt;
					font-weight: 700;
				}
				date := DatePanel {}
			}

			StatusPanel { message: root.status; }
		}
		Rectangle { height: 2px; background: #32383e;}
		
		// Departure panels
		VerticalLayout {
			alignment: stretch;

			DeparturePanel {
				schedule: root.schedule-into-city;
				direction: "Stadt";
				direction-color: #E6B867;
			}
			DeparturePanel {
				schedule: root.schedule-from-city;
				direction: "A3";
				direction-color: #3287EB;
				vertical-stretch: 2;
			}
		}	
	}

	// Bus stop list
	Rectangle {
		height: 32px * busstop-panel.data.length;
		width: 350px;
		padding: 10px;

		x: parent.width - self.width - self.padding;
		y: parent.height - self.height - self.padding;
		z: 10;

		border-radius: 2px;
		border-width: 2px;
		border-color: #555;
		background: #333;

		cache-rendering-hint: true;

		busstop-panel := BusStopList {
			text-color: #888;

			padding: 5px;
			padding-left: 7px;
			padding-right: self.padding-left;
		}
	}
}
