
export component Date inherits Text {
	in property <string> date: "PRSNT DAY...";

	text: root.date;
	color: #FFF;
	font-size: 30pt;
	font-weight: 600;
}

export component Time inherits HorizontalLayout {
	in property <string> time: "PRSNT TIME...";
	in property <int> secs: 27;

	alignment: end;
	spacing: 4px;
	Text {
		text: root.time;
		color: #FFF;
		font-size: 30pt;
		font-weight: 600;
	}
	Rectangle {
		width: 4px;
		background: #555;
		height: 31px;
		y: 13px;
		Rectangle {
			height: parent.height * root.secs / 60;
			y: parent.height - self.height;
			background: #bbb;
		}
	}
}

export component DateTimePanel inherits HorizontalLayout {
	in property <string> title;
	in property <string> date: "PRSNT DAY...";
	in property <string> time: "PRSNT TIME...";
	in property <int> secs: 27;

	//alignment: space-between;
	spacing: 10px;

	Text {
		text: root.title;
		color: #FFF;
		font-size: 30pt;
		font-weight: 700;
	}

	HorizontalLayout {
		alignment: end;
		spacing: 4px;

		Text {
			text: root.date;
			color: #FFF;
			font-size: 30pt;
			font-weight: 600;
		}
		Text {
			text: " - ";
			color: #FFF;
			font-size: 30pt;
			font-weight: 600;
		}
		Text {
			text: root.time;
			color: #FFF;
			font-size: 30pt;
			font-weight: 600;
		}
		Rectangle {
			width: 4px;
			background: #555;
			height: 31px;
			y: 13px;
			Rectangle {
				height: parent.height * root.secs / 60;
				y: parent.height - self.height;
				background: #bbb;
			}
		}
	}
}

export component StatusPanel inherits Rectangle {
	in property <string> message: "Initialising...";

	background: #3e444c;
	border-color: #fa5;
	border-width: 1px;
	border-radius: 2px;
	clip: true;
	VerticalLayout {
		padding: 1px;
		alignment: start;
		if root.message != "" : Text {
			text: root.message;
			font-size: 16pt;
			color: #fa5;
			wrap: word-wrap;
			vertical-alignment: center;
			horizontal-alignment: center;
		}
	}
}
