export global State  {
	in property <int> time: 1696420000+2000;
	
	pure callback fmt-float(float, int) -> string;
	pure callback fmt-time(int) -> string;
	pure callback fmt-date(int) -> string;
	pure callback dur-in-days(int) -> float;
	pure callback is-midnight(int) -> bool;

	// Dev helpers
	fmt-float(f, i) => { return Math.round(f * pow(10, i)) / pow(10, i) + "."; }
	fmt-time(time) => { return "13:37"; }
	fmt-date(date) => { return "Someday, 24.07"; }
	dur-in-days(dur) => {
	    return dur/86400.0;
	}
	is-midnight(time) => {
		return mod(floor((time+3600*2)/3600), 24) == 0 && mod(floor((time+3600*2)/60), 60) == 0;
	}
	//------------

	public pure function time-progress(current: int, start: int, end: int) -> float  {
		return min(max(0.0, (current - start)/(end - start)), 1.0);
	}

	public pure function is-whole-day(start: int, end: int) -> bool  {
		return abs(dur-in-days(end - start)) == 0;
	}
}


export component Date inherits HorizontalLayout {
	alignment: start;
	Text {
		text: State.fmt-date(State.time);
		color: #FFF;
		font-size: 1.1rem;
		font-weight: 600;
	}
}

export component Time inherits HorizontalLayout {
	in property <int> secs: mod(State.time, 60);

	alignment: start;
	spacing: 0.3rem;
	Text {
		text: State.fmt-time(State.time);
		color: #FFF;
		font-size: 1.1rem;
		font-weight: 600;
	}
	Rectangle {
		background: #555;
		width: 0.5rem;
		height: 0.9rem;
		y: 0.35rem;
		Rectangle {
			height: parent.height * root.secs / 60;
			y: parent.height - self.height;
			background: root.secs < 50 ? #bbb : #eb2;
		}
	}
}

export component StatusPanel inherits Rectangle {
	in property <string> message: "Initialising...";

	background: #3e444c;
	border-color: #fa5;
	border-width: 1px;
	border-radius: 2px;
	clip: true;
	VerticalLayout {
		padding: 1px;
		alignment: start;
		if root.message != "" : Text {
			text: root.message;
			font-size: 16pt;
			color: #fa5;
			wrap: word-wrap;
			vertical-alignment: center;
			horizontal-alignment: center;
		}
	}
}
