import { Date as DatePanel, Time as TimePanel, StatusPanel }
	from "shared.slint";

import { TimeBlock, TimeBlockPanel, State }
	from "table.slint";

import { Headline, NewsPanel }
	from "news.slint";

export { State }

global Language  {
	in property <string> title-regular: "Stundenplan";
	in property <string> title-exam: "Prüfungsplan";
	
	in property <string> lesson-break: "Vorlesungsfrei\n¯\\_(ツ)_/¯";
	
	in property <string> timeoff-regular: "Feierabend!";
	in property <string> timeoff-exam: "Einfach morgen weiter lernen...";
}

export struct Headline  {
	title: string,
	date: string,
	time: string,
}

export component App inherits Window {
	in property <string> date <=> date.date;
	in property <string> time <=> time.time;
	in property <int> secs <=> time.secs;

	in property <string> timetable_status;
	in property <string> headlines_status;

	in property <bool> loading: true;
	in property <bool> time-off: false;
	in property <int> exam-time-left: 0;
	in property <string> exam-time-left-str;

	private property <bool> exam-phase: root.exam-time-left > 0;
	private property <bool> lecture-break: root.time-blocks.length == 0;
	private property <bool> no-lectures: root.time-off || lecture-break;



	in property <[TimeBlock]> time_blocks;
	in property <[Headline]> headlines;

	title: root.exam-phase ? Language.title-exam : Language.title-regular;
	background: #272b30;
	default-font-family: "Noto Sans";
	default-font-size: 32px;
	min-height: 100px;
	min-width: 300px;
	max-width: 10000px;

	VerticalLayout {
		alignment: start;
		padding-left: 10px;
		padding-right: 10px;

		HorizontalLayout {
			alignment: space-between;
			spacing: 4px;

			time := TimePanel {}
			Text {
				text: root.title;
				color: root.exam-phase ? #f66 : #FFF;
				font-size: 30pt;
				font-weight: 700;

				horizontal-alignment: center;
			}
			date := DatePanel {}
		}

		Rectangle { height: 2px; background: #32383e;}
		StatusPanel { message: root.timetable_status; }

		lecture-box := VerticalLayout {
			if !root.time-off :
				Flickable {
					z: 10;

					VerticalLayout {
						alignment: start;
						spacing: 5px;

						for block[idx] in root.time_blocks : VerticalLayout {
							property <bool> is_first: idx == 0;
							cache-rendering-hint: true;

							if block.date != "" && !self.is_first : VerticalLayout {
								padding-top: 4px;
								padding-bottom: 8px;
								Rectangle { height: 1px; background: #3e444c.brighter(100%); }
							}
							TimeBlockPanel {
								data: block;
								highlight: false; // root.exam-phase && is_first;
							}
						}
					}
				}
		}


		if root.no-lectures : Rectangle {
			//border-color: #55f; border-width: 3px;
			width: 100%;
			height: 100%;
			VerticalLayout {
				alignment: space-around;

				if root.loading : Text {
					text: "Loading...";
					font-size: 102pt;
					color: #FFFFFF33;

					horizontal-alignment: center;
					vertical-alignment: center;
				}

				if root.time-off && !root.lecture-break:
					VerticalLayout {
						alignment: center;

						Text {
							text: root.exam-phase ? Language.timeoff-exam : Language.timeoff-regular;
							font-size: 80pt;

							color: #fa5;
							wrap: word-wrap;
							vertical-alignment: center;
							horizontal-alignment: center;
						}
						if root.exam-phase :
							Text {
								text: "(Erlösung in "+ root.exam-time-left-str +" Tagen)";
								font-size: 30pt;

								color: #FFFFFF88;
								wrap: word-wrap;
								vertical-alignment: center;
								horizontal-alignment: center;
							}
					}
				if !root.loading && root.lecture-break :
					VerticalLayout {
						alignment: center;

						Text {
							text: Language.lesson-break;
							font-size: 80pt;

							color: #fa5;
							wrap: word-wrap;
							vertical-alignment: center;
							horizontal-alignment: center;
						}
					}

			}
		}
	}

	headline-box := VerticalLayout {
		height: 56px * min(root.headlines.length, 4);
		padding: 7px;
		y: parent.height - self.height;
		z: 1;

		StatusPanel { message: root.headlines_status; }
		NewsPanel { data: root.headlines; }
	}
	if lecture-box.height > 0 : Rectangle {
		height: 150px;
		width: lecture-box.width;
		x: lecture-box.x;
		y: headline-box.y - self.height * 95%;
		background: @linear-gradient(0deg, #272b30FF 0%, #272b30FF 5%,#272b3000 100%);
	}
	Rectangle {
		height: root.height - headline-box.y;
		width: root.width;
		x: lecture-box.x;
		y: headline-box.y;
		background: root.background;
	}
}
