global Language  {
	in property <string> title: "Busfahrplan";

	in property <string> now: "jetzt";
	in property <string> minute-abbr: "min";
	in property <string> hour-abbr: "h";

	in property <string> departure_at: "Abfahrt um";
	in property <string> departure_in: "in";
	in property <string> line: "Linie";
	in property <string> direction: "Richtung ";
	in property <string> stop: "Haltestelle";
}

global Style  {
	in property <string> font-family: "Noto Sans";
	in property <brush> text-color: #fff;

	in property <brush> block-background: #32383e;

	in property <color> dep-delay-color: #f89406;
	in property <color> dep-time-color-chill: #62c462;
	in property <color> dep-time-color-pushy: #f89406;
	in property <color> dep-time-color-crit: #ee5f5b;
	in property <color> dep-time-color-missed: #aaaaaa;
	
	in property <color> line-background: #111;
	in property <color> line-border-color: #EDE13B;
	in property <color> line-text-color: root.line-border-color;

}

// API
//#####
export struct BusStop  {
	name: string,
	color: color,
	distance: int, // in m
	time_min: int, // in minutes
	time_max: int, // in minutes
}

export struct Departure  {
	time: string,
	delay: int,
	deadline: int,

	line: string,
	final_stop: string,

	local_stop_idx: int,
}

export global State  {
    in property<int> time;
	in property <[BusStop]> local-stop-list;
}

component EntryPanel inherits Rectangle {
	in property <Departure> data;
	in property <BusStop> local-stop: State.local-stop-list[root.data.local-stop-idx];

	in property <color> text-color: Style.text-color;
	in property <color> shade: root.local-stop.color.darker(70%);

	background: @linear-gradient(90deg,
		root.shade 0%,
		Style.block-background 10%,
		Style.block-background 80%,
		root.shade 100%);

	// Base
	HorizontalLayout {
		alignment: space-between;
		padding-left: 10px;
		padding-right: 10px;
		padding-top: 5px;
		padding-bottom: 5px;
		spacing: 20px;

		// Departure time
		HorizontalLayout {
			spacing: 15px;
			width: 265px;

			// absolute
			HorizontalLayout {
				alignment: start;
				spacing: 5px;
				width: 150px;

				Text {
					text: root.data.time;
					color: root.text-color;
				}
				if root.data.delay != 0 : Text {
					text: (root.data.delay > 0 ? "+" : "-") + root.data.delay;
					color: Style.dep-delay-color;
					font-size: 20pt;
					vertical-alignment: center;
				}
			}
			// remaining
			Text {
				property <int> remaining: root.data.deadline - State.time;

				text: self.remaining == 0 ? Language.now :
					abs(self.remaining) <= 60 ? self.remaining + " " + Language.minute-abbr :
					floor(self.remaining/6)/10.0 + " " + Language.hour-abbr;
				font-size: 24pt;
				font-weight: 600;
				vertical-alignment: center;
				horizontal-alignment: left;

				color:
					self.remaining < root.local-stop.time-min ? Style.dep-time-color-missed :
					self.remaining < (root.local-stop.time-min+root.local-stop.time-max)/2 ? Style.dep-time-color-crit :
					self.remaining < root.local-stop.time-max ? Style.dep-time-color-pushy :
						Style.dep-time-color-chill;
				
				min-width: 100px;
			}
		}

		// Destination
		HorizontalLayout {
			alignment: start;
			spacing: 10px;
			min-width: 100px;

			// Route
			HorizontalLayout {
				alignment: end;
				preferred-width: 130px;

				Rectangle {
					max-width: 130px;
					min-width: 56px;
					
					background: Style.line-background;
					border-color: Style.line-border-color;
					border-radius: 4px;
					border-width: 2px;

					clip: true;
					HorizontalLayout {
						padding-left: 5px;
						padding-right: 5px;
						Text {
							text: root.data.line;
							color: Style.line-text-color;
							font-family: "Noto Sans Mono";
							horizontal-alignment: center;
						}
					}
				}
			}
			// Final stop
			Text {
				text: root.data.final-stop;
				overflow: elide;
				color: root.text-color;

				preferred-width: 450px;
				min-width: 100px;
			}
		}
		// Local stop
		Text {
			text: root.local-stop.name;
			overflow: elide;
			color: root.text-color.darker(0.5);
			font-size: 18pt;
			font-weight: 300;

			horizontal-alignment: right;
			vertical-alignment: center;

			width: 150px;
		}
	}
}

export component SchedulePanel inherits Rectangle {
	in property <[Departure]> schedule;
	in property <string> direction;
	in property <color> direction-color;
	
	VerticalLayout {
		alignment: start;
		spacing: 2px;

		// Header
		header := HorizontalLayout {
			alignment: space-between;
			padding-left: 10px;
			padding-right: 10px;
			spacing: 20px;

			// Departure time
			HorizontalLayout {
				alignment: start;
				width: 265px;

				// absolute
				Text {
					text: Language.departure-at;
					color: Style.text-color;
					font-weight: 600;
				}

				// remaining
				Text {
					text: "/" + Language.departure-in;
					color: Style.text-color;
					font-weight: 300;
					font-size: 24px;
					vertical-alignment: bottom;
				}
			}

			// Destination
			HorizontalLayout {
				preferred-width: 580px;
				padding-left: 50px;
				spacing: 20px;

				// Route
				Text {
					text: Language.line;
					color: Style.text-color;
					font-weight: 600;
				}

				// Final stop
				Text {
					text: Language.direction + root.direction;
					color: root.direction-color;
					font-weight: 700;
				}
			}

			// Local stop
			Text {
				text: Language.stop;
				color: Style.text-color.darker(0.8);
				font-weight: 400;
				horizontal-alignment: right;

				width: 150px;
			}
		}

		list := Flickable {		
		 	VerticalLayout {
		 		alignment: start;
				spacing: 2px;

				for departure in root.schedule : EntryPanel {
					data: departure;
				}
			}
		}
	}

	Rectangle {
		height: min(100px, root.height - root.min-height);
		x: list.x;
		y: list.y + list.height - self.height + 1px;
		
		background: @linear-gradient(0deg, #272b30FF 0%, #272b30FF 15%,#272b3000 100%);
	}
}


export component BusStopList inherits VerticalLayout {
	in property <[BusStop]> data: State.local_stop_list;
	in property <int> idx-updating: -1;

	in property <color> text-color: #888;

	for bus-stop[idx] in root.data : HorizontalLayout {
		alignment: space-between;
		spacing: 5px;

		Text {
			text: bus-stop.name;
			font-size: 20px;
			font-weight: idx == idx-updating ? 700 : 500;
			color: bus-stop.color;
			vertical-alignment: center;

			width: 140px;
		}
		Text {
			text: bus-stop.distance + " m";
			font-size: 16px;
			color: root.text-color;
			vertical-alignment: center;
			//width: 50px;
		}
		Text {
			text: "(" + bus-stop.time_min + " - " + bus-stop.time_max + " " + Language.minute-abbr + ")";
			font-size: 16px;
			color: root.text-color;
			vertical-alignment: center;
			//width: 60px;
		}
	}
}


export component Panel inherits Rectangle {
	in property <[Departure]> schedule-into-city;
	in property <[Departure]> schedule-from-city;

	background: #272b30;

	// Departure panels
	VerticalLayout {
		alignment: stretch;

		SchedulePanel {
			schedule: root.schedule-into-city;
			direction: "Stadt";
			direction-color: #E6B867;
			vertical-stretch: 2;
		}
		SchedulePanel {
			schedule: root.schedule-from-city;
			direction: "A3";
			direction-color: #3287EB;
			vertical-stretch: 2;
		}
	}

	// Bus stop list
	Rectangle {
		height: 32px * busstop-panel.data.length;
		width: 380px;
		padding: 10px;

		x: parent.width - self.width - self.padding;
		y: parent.height - self.height - self.padding;
		z: 10;

		border-radius: 2px;
		border-width: 2px;
		border-color: #555;
		background: #333;

		cache-rendering-hint: true;

		busstop-panel := BusStopList {
			text-color: #888;

			padding: 5px;
			padding-left: 7px;
			padding-right: self.padding-left;
		}
	}
}
