// TODO: rewrite
// - rem usage

global Language  {
	in property <string> title-regular: "Stundenplan";
	in property <string> title-exam: "Prüfungsplan";
	
	in property <string> lesson-break: "Vorlesungsfrei\n¯\\_(ツ)_/¯";
	
	in property <string> timeoff-regular: "Feierabend!";
	in property <string> timeoff-exam: "Einfach morgen weiter lernen...";
	in property <string> timeoff-exam-end: "Erlösung in {} Tagen...";
}

struct TextBoxStyle {
	font-family: string,
	font-size-factor: float,
	text-color: brush,
	background: brush,
}

export global Style {
	in property <string> font-family: "Noto Sans";
	in property <brush> text-color: #fff;
	in property <color> exam-color: #b10000;

	in property <brush> block-background: #32383e;
	in property <color> block-border-color: #000;
	in property <color> block-border-color-highlight: #b10000;
	in property <color> block-hightlight: #0059b1;
	in property <brush> header-background: #3e444c;
	in property <brush> header-background-date:
		@linear-gradient(90deg,
			root.block-hightlight.darker(33%) 0%, root.block-hightlight.darker(33%) 25%,
			root.header-background 40%, root.header-background 100%);

	in property <brush> entry-background: root.block-background;

	//! All other sizes are relative to this
	in property <length> row-height: 42px;
	in property <length> header-height: root.row-height * 110%;

	in property <TextBoxStyle> lecture: {
		font-family: "Noto Sans Mono",
		font-size-factor: 0.80,
		text-color: root.text-color,
		// default
		background: @linear-gradient(0, #419641.brighter(0.35), #419641),
	};

	in property <TextBoxStyle> exam: {
		font-family: root.lecture.font-family,
		font-size-factor: root.lecture.font-size-factor,
		text-color: root.lecture.text-color,
		// default
		background: @linear-gradient(0, root.exam-color.brighter(0.35), root.exam-color),
	};

	in property <TextBoxStyle> location: {
		font-family: root.lecture.font-family,
		font-size-factor: root.lecture.font-size-factor,
		text-color: root.text-color,
		// default
		background: @linear-gradient(0, #4A78D3.brighter(0.35), #4A78D3),
	};
	in property <TextBoxStyle> course: {
		font-family: root.font-family,
		font-size-factor: 0.80,
		text-color: root.text-color,		
		// default
		background: root.location.background,
	};
}

// API
//#####
export global State  {
	in property <int> day-time; // in minutes
}

export struct Course  {
	title: string,
	color: color,
}

export struct Location  {
	title: string,
	color: color,
}

export struct Entry  {
	title: string,
	abbr: string,
	lecturers: string,
	locations: [Location],
	courses: [Course],
	is_exam: bool,
}

export struct TimeBlock  {
	date: string,
	time: string,
	entries: [Entry],
}

// GUI panels
//############
component EntryPanel inherits Rectangle {
	in property <Entry> data;
	in property <TextBoxStyle> style: root.data.is_exam ? Style.exam : Style.lecture;

	background: Style.entry-background;
	height: Style.row-height;

	HorizontalLayout {
		alignment: space-between;

		HorizontalLayout {
			alignment: start;
			spacing: parent.height * 10%;

			HorizontalLayout {
				alignment: start;
				padding: parent.height * 10%;
				padding-right: 0px;
				spacing: parent.height * 10%;

				// Lecture abbreviation
				Rectangle {

					min-width: parent.height * 160%;
					max-width: parent.height * 250%;
					border-radius: parent.height * 5%;
					background: root.style.background;

					VerticalLayout {
						padding: parent.height * 5%;
						lecture-text := Text {
							text: root.data.abbr;

							color: root.style.text-color;
							font-family: root.style.font-family;
							font-size: title-text.font-size * root.style.font-size-factor;

							overflow: elide;
							vertical-alignment: center;
							horizontal-alignment: center;
						}
					}
				}

				// Locations
				HorizontalLayout {
					spacing: parent.height * 3%;
					min-width: parent.height * 150%;

					for location[idx] in root.data.locations : Rectangle {
						max-width: parent.height * 350%;
						border-radius: parent.height * 5%;
						background: location.color == #000 ?
							Style.location.background :
							@linear-gradient(0, location.color.brighter(0.35), location.color);

						VerticalLayout {
							property <length> pad-inner: parent.height * 10%;
							property <length> pad-outer: parent.height * 20%;

							padding-left: idx == 0 ? self.pad-outer : self.pad-inner;
							padding-right: idx == root.data.locations.length - 1 ? self.pad-outer : self.pad-inner;
							location-text := Text {
								text: location.title;

								color: Style.location.text-color;
								font-family: Style.location.font-family;
								font-size: title-text.font-size * Style.location.font-size-factor;

								vertical-alignment: center;
								horizontal-alignment: center;

								letter-spacing: root.data.locations.length > 1 ? parent.pad-inner * -25% : 0px;
							}
						}
					}
				}
			}

			// Lecture
			HorizontalLayout {
				alignment: start;
				spacing: parent.height * 4%;

				// Title
				title-text := Text {
					text: root.data.title;

					color: Style.text-color;
					font-family: Style.font-family;
					font-size: parent.height * 65%;

					overflow: elide;
					vertical-alignment: center;
				}

				// Lecturer
				Text {
					text: root.data.lecturers;

					color: Style.text-color.darker(0.7);
					font-family: Style.font-family;
					font-size: title-text.font-size * 80%;

					vertical-alignment: center;
				}
			}
		}

		// Courses
		HorizontalLayout {
			alignment: end;
			padding: parent.height * 10%;
			padding-left: 0px;
			spacing: parent.height * 10%;

			for course[idx] in root.data.courses : Rectangle {
				border-radius: parent.height * 5%;
				background: course.color == #000 ?
					Style.course.background :
					@linear-gradient(0, course.color.brighter(0.35), course.color);

				VerticalLayout {
					property <length> pad-inner: parent.height * 12%;
					property <length> pad-outer: parent.height * 20%;

					padding-left: idx == 0 ? self.pad-outer : self.pad-inner;
					padding-right: idx == root.data.courses.length - 1 ? self.pad-outer : self.pad-inner;

					course-text := Text {
						text: course.title;

						color: Style.course.text-color;
						font-family: Style.course.font-family;
						font-size: title-text.font-size * Style.course.font-size-factor;
						
						vertical-alignment: center;
						horizontal-alignment: center;
						letter-spacing: root.data.courses.length > 1 ? parent.pad-inner * -25% : 0px;
					}
				}
			}
		}
	}
}

export component TimeBlockPanel inherits Rectangle {
	in property <TimeBlock> data;
	in property <bool> highlight;

	background: Style.block-background;
	border-color: root.highlight ? Style.block-border-color-highlight : Style.block-border-color;
	border-width: 2px;
	border-radius: 2px;
	clip: true;

	VerticalLayout {
		padding: 1px;
		alignment: start;

		Rectangle {
			height: Style.header-height;
			background:
				root.data.date != ""
				? Style.header-background-date
				: Style.header-background;

			HorizontalLayout {
				padding-left: parent.height * 18%;
				Text {
					text: root.data.date;

					color: Style.text-color;
					font-size: parent.height * 65%;
					font-weight: 600;
					
					vertical-alignment: center;
					horizontal-alignment: left;
				}
			}
			HorizontalLayout {
				Text {
					text: root.data.time;

					color: Style.text-color;
					font-size: parent.height * 65%;
					font-weight: 600;
					
					vertical-alignment: center;
					horizontal-alignment: center;
				}
			}
		}
		VerticalLayout {
			alignment: start;
			for lecture in root.data.entries : VerticalLayout {
				Rectangle { height: 2%; background: Style.block-border-color;}
				EntryPanel { data: lecture; }
			}
		}
	}
}


export component Panel inherits VerticalLayout {
	in property <[TimeBlock]> list;

	in property <bool> loading: false;

	in property <bool> time-off: false;
	in property <int> exam-time-left: 0;
	in property <string> exam-time-left-str;
	in property <string> o-time-left-str;

	private property <bool> exam-phase: root.exam-time-left > 0;
	private property <bool> lecture-break: root.list.length == 0;
	private property <bool> no-lectures: root.time-off || lecture-break;

	//background: #272b30;
	alignment: start;

	if !root.time-off :	Flickable {
		z: 10;

		VerticalLayout {
			alignment: start;
			spacing: 5px;

			for block[idx] in root.list : VerticalLayout {
				property <bool> is_first: idx == 0;
				cache-rendering-hint: true;

				if block.date != "" && !self.is_first : VerticalLayout {
					padding-top: 4px;
					padding-bottom: 8px;
					Rectangle { height: 1px; background: #3e444c.brighter(100%); }
				}
				TimeBlockPanel {
					data: block;
					highlight: false; // root.exam-phase && is_first;
				}
			}
		}
	}

	if root.no-lectures : Rectangle {
		//border-color: #55f; border-width: 3px;
		width: 100%;
		height: 100%;
		VerticalLayout {
			alignment: space-around;

			if root.time-off && !root.lecture-break:
				VerticalLayout {
					alignment: center;

					Text {
						text: root.exam-phase ? Language.timeoff-exam : Language.timeoff-regular;
						font-size: 80pt;

						color: #fa5;
						wrap: word-wrap;
						vertical-alignment: center;
						horizontal-alignment: center;
					}
					if root.exam-phase : VerticalLayout {
						alignment: space-between;
						spacing: 120px;

						Text {
							text: "(Erlösung in "+ root.exam-time-left-str +" Tagen)";
							font-size: 30pt;

							color: #FFFFFF88;
							wrap: word-wrap;
							vertical-alignment: center;
							horizontal-alignment: center;
						}
						Text {
							text: "\"Kann nicht, muss weiter lernen\"";
							font-size: 40pt;

							color: #fa5;
							wrap: word-wrap;
							vertical-alignment: center;
							horizontal-alignment: center;
						}
					}
				}
			if !root.loading && root.lecture-break :
				VerticalLayout {
					alignment: center;

					Text {
						text: Language.lesson-break;
						font-size: 80pt;

						color: #fa5;
						wrap: word-wrap;
						vertical-alignment: center;
						horizontal-alignment: center;
					}
				}

			if root.o-time-left-str != "" :
				VerticalLayout {
					alignment: end;
					padding: 10px;

					HorizontalLayout {
						alignment: center;
						Image {
							source: @image-url("ozora.png");
							colorize: #FFFFFF55;
							width: 150px;
						}
					}
					Text {
						text: root.o-time-left-str;
						font-size: 25pt;

						color: #FFFFFF55;
						wrap: word-wrap;
						vertical-alignment: center;
						horizontal-alignment: center;
					}
				}
		}
	}

}
