export struct Headline {
	title: string,
	date: string,
	time: string,
}

export component NewsPanel inherits Rectangle {
	in property <[Headline]> data;

	in property <color> text-color: #fff;

	background: #3e444c;
	border-color: #000;
	border-width: 4px;
	border-radius: 2px;
	clip: true;

	Flickable {
		VerticalLayout {
			alignment: start;

			for headline in root.data : VerticalLayout {
				cache-rendering-hint: true;

				Rectangle { height: 1px; background: root.border-color; }
				HorizontalLayout {
					alignment: start;
					spacing: 10px;
					padding-top: 2px;
					padding-bottom: root.padding-top;
					padding-left: 8px;
					padding-right: root.padding-left;

					VerticalLayout {
						Text {
							text: headline.date;
							color: root.text-color;
							font-weight: 700;
							font-size: 12pt;
							horizontal-alignment: right;
						}
						Text {
							text: headline.time;
							color: root.text-color;
							font-weight: 500;
							font-size: 12pt;
							horizontal-alignment: right;
						}
					}
					Text {
						text: headline.title;
						color: root.text-color;
						overflow: elide;
					}
				}
			}
			Rectangle { height: 5px; background: root.border-color; }
		}
	}
}
